algoritmo "Creuza01"
      //Creuza não sabe quantas velinhas tem que estar no seu bolo de aniversário
var
      anascimento, aatual, v: inteiro

inicio
      Escreva("Digite o ano que nasceu: ")
      Leia(anascimento)
      Escreva("Digite em que ano você está: ")
      Leia (aatual)
      v <- (aatual - anascimento)
      Escreval("Parabéns! Você tem ", v, " anos!")
      Escreval("A quantidade de velinhas para o seu bolo, são de: ", v, " velinhas!")

fimalgoritmo
