algoritmo "Idade"
      //Creuza não sabe quantas velinhas tem que estar no seu bolo de aniversário
var
      nascimento, ano, v: inteiro

inicio
      Escreval("Digite o ano que nasceu: ")
      Leia(nascimento)
      Escreval("Digite em que ano você está: ")
      Leia (ano)
      v <- (ano - nascimento)
      Escreval("No ano de", ano, " você estará com ", v, " anos de idade")
      Se (v >= 21) Entao
      
      Escreval("E você já é de maior!")
      
      FimSe



fimalgoritmo
